export {
  Commenting,
  CommentMark,
  QuoteMark,
  COMMENT_MARK_NAME,
  QUOTE_MARK_NAME,
  addCommentMark,
  canComment,
  removeCommentMark,
  findCommentRanges,
  findQuoteRanges,
  quoteCommentedPassage,
  unquotePassage,
  commentedSlice,
  touchesAnchors,
  type CommentRange,
  type QuoteRange,
  type CommentingOptions,
} from './comment-mark';
